### ISSUE TITLE
Get all playlists of a given channel

### ISSUE THREAD

**Issue by jy95** [jasonhaxstuff/better-youtube-api#5]
Hello,

Thanks for your hard work : this library is by far the cleanest I have seen for this domain ;)

Like the title said, I would like to get all the playlists for a channel ( for exemple mine : 
UCG0N7IV-C43AM9psxslejCQ ). Your [searchPlaylists](https://bbothell.me/better-youtube-api/docs/classes/youtube.html#searchplaylists) function doesn't include a parameter for that.

From what I read on the [docs](https://developers.google.com/youtube/v3/docs/search/list) , you only have to include the optional parameter **channelId** in your requests. ( [demo url](https://developers.google.com/youtube/v3/docs/search/list?apix_params=%7B%22part%22%3A%22snippet%22%2C%22channelId%22%3A%22UCG0N7IV-C43AM9psxslejCQ%22%2C%22type%22%3A%22playlist%22%7D) )

Thank you in advance

**Comment by jasonhaxstuff** [comment]
Added in 2983f19 : 
`Channel#fetchPlaylists` and `YouTube#getChannelPlaylists`
Released in v2.1.2
